# Generated by Django 4.2 on 2026-04-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_companylogo'),
        ('accounts', '0008_customuser_salary'),
    ]

    operations = [
    ]
