# Generated by Django 4.2 on 2026-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_0008_companylogo_0008_customuser_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='bypass_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
