"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import socket
import warnings
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me")

# RAZORPAY TEST KEYS
RAZORPAY_KEY_ID = "rzp_test_SXxeb9ZQt4ndd5"
RAZORPAY_KEY_SECRET = "BbwMnLgv3liaosjUbw5uXBO2"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [host for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if host]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'attendance',
    'leave',
    'dashboard',
    'payroll',
]


AUTH_USER_MODEL = 'accounts.CustomUser'

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


def _sqlite_database():
    return {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


def _is_truthy_env(value: str | None) -> bool:
    return str(value).lower() in {"1", "true", "yes", "on"}


def _can_reach_db_host(host: str | None, port: str | int | None) -> bool:
    if not host:
        return False
    try:
        with socket.create_connection((host, int(port or 5432)), timeout=2):
            return True
    except OSError:
        return False


def _use_local_db_fallback(reason: str):
    warnings.warn(f"{reason} Falling back to local SQLite database.")
    return _sqlite_database()


force_local_db = _is_truthy_env(os.getenv("FORCE_LOCAL_DB"))
enable_db_fallback = _is_truthy_env(os.getenv("ENABLE_LOCAL_DB_FALLBACK", "true"))
ssl_require = _is_truthy_env(os.getenv("DB_SSL_REQUIRE", "true"))

if force_local_db:
    DATABASES = _sqlite_database()
else:
    database_url = os.getenv("DATABASE_URL")
    if database_url:
        try:
            parsed_db = dj_database_url.parse(
                database_url,
                conn_max_age=600,
                ssl_require=ssl_require,
            )
            db_host = parsed_db.get("HOST")
            db_port = parsed_db.get("PORT", 5432)
            if enable_db_fallback and not _can_reach_db_host(db_host, db_port):
                DATABASES = _use_local_db_fallback(
                    f"DATABASE_URL host '{db_host}:{db_port}' is unreachable."
                )
            else:
                DATABASES = {"default": parsed_db}
        except Exception as exc:
            if enable_db_fallback:
                DATABASES = _use_local_db_fallback(
                    f"Failed to parse DATABASE_URL ({exc})."
                )
            else:
                raise
    else:
        db_name = os.getenv("DB_NAME")
        db_user = os.getenv("DB_USER")
        db_password = os.getenv("DB_PASSWORD")
        db_host = os.getenv("DB_HOST")
        db_port = os.getenv("DB_PORT", "5432")

        if all([db_name, db_user, db_password, db_host]):
            if enable_db_fallback and not _can_reach_db_host(db_host, db_port):
                DATABASES = _use_local_db_fallback(
                    f"Configured Postgres host '{db_host}:{db_port}' is unreachable."
                )
            else:
                DATABASES = {
                    "default": {
                        "ENGINE": "django.db.backends.postgresql",
                        "NAME": db_name,
                        "USER": db_user,
                        "PASSWORD": db_password,
                        "HOST": db_host,
                        "PORT": db_port,
                    }
                }
        else:
            DATABASES = _sqlite_database()



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}
