# Generated by Django 4.2 on 2026-01-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='user',
            new_name='CustomUser',
        ),
    ]
